name: Periodic Health Check
on:
  schedule:
  - cron:  '0 0 * * *'
jobs:
  periodic_health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://www.youtube.com/
          follow-redirect: no
          max-attempts: 3
          retry-delay: 5s